# 사이트 기본 설정
site_name: Lua 한국어 위키
site_url: https://qwreey75.github.io/luakrdoc/
site_author: Qwreey and more
site_description: lua 5.3 wiki for korean

# 리포 설정
repo_name: luakrdoc
repo_url: https://github.com/qwreey75/luakrdoc
edit_uri: ""

# 벤치 설정-사이트dir 설정, 저장소 하나로 관리하기 위해서 이렇게 씀
remote_branch: master
docs_dir: docroot
site_dir: docs

# 검색엔진 설정
# TODO : 검색 엔진 언어 변경
lang: multi #한국어가 없고 중국어도 없어서 일단 일어로 먹여봄
min_search_length: 2

# 테스팅 사이트 설정(로컬 서버)
dev_addr: '127.0.0.1:8000'

# 추가 Css
extra_css:
    - extra/page

# 사이드바
nav:
    - 시작하기: 'index.md'
    

# 테마링
theme:
    # 기본 설정
    name: material
    custom_dir: overrides

    # 테마
    palette:
        scheme: slate
        primary: purple
        accent: deep purple

    # 세부기능 Flag
    features:
        - toc.integrate

    # 결과 없음 페이지
    static_templates:
      - 404.html

    # 언어/폰트
    language: kr
    font:
        text: Roboto
        code: Roboto Mono

    # 아이콘
    favicon: assets/LUAICON_TP.png
    logo: assets/LUAICON_TP.png

    # 일부 설정
    include_search_page: false
    search_index_only: true

# Markdown 플러그인
markdown_extensions:
    - pymdownx.tabbed # 탭
    - admonition # 노트라인
    - pymdownx.details # 더보기(확장 가능한 라벨)
    - abbr # 줄임말 표현 세부정보 붇이기
    - attr_list # 리스트 추가사항
    - def_list # 기본 리스트

    # 기초 설정
    - codehilite: # 코드 자동분석 끄기
          guess_lang: false
    - toc: # 부분 링크 허용
          permalink: true
    - pymdownx.emoji: # 이모지 불러오기
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.tasklist: # 체크박스 불러오기
          custom_checkbox: true
    
    # 나도 잘 모르겠는 기타 설정
    - meta # 메타데이터 관련
    - pymdownx.inlinehilite # `인라인 코드`
    - footnotes # 바닥글
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
    - pymdownx.betterem:
          smart_enable: all
